import { Download } from 'lucide-react'
import '../globals.css'
import Link from "next/link"
// import { getPages } from '@/sanity/sanity-utils';

export const metadata = {
  title: 'Muhammad Mohsin',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const pages = await getPages();

  return (
    <html lang="en">
      <body className="py-8 bg-black overflow-x-hidden">
        <header className="w-screen flex flex-col text-white justify-between">
          <Link href="/" className="uppercase mx-8 pb-6 bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">Muhammad Mohsin</Link>
          <div className='w-full h-64 overflow-hidden object-cover mx-0'>
              <img src="https://i.postimg.cc/jdXQY2sD/9-SS0203-Copy.jpg" alt="cover" className='w-screen'/>
          </div>
          <div className='flex flex-col mt-3 py-3 mx-8 mb-4 gap-5 justify-between lg:flex-row'>
            <div className=' flex items-center justify-center '>
              <img className='ml-0 lg:ml-3' src="https://i.postimg.cc/kMZ8MBFN/IMG-0928.png" alt="hello" width="100" />
            </div>
            <div className='flex flex-col items-center text-center lg:text-left lg:items-start justify-center'>
              <h1 className='font-bold'>Muhammad Mohsin</h1>
              <h5>I make your boring clips to something more enjoyable !!</h5>
            </div>
            <div className='w-36'></div>
            <div className='flex w-full lg:w-fit items-center lg:mr-7 justify-center'>
              <Link className='bg-red-600 px-7 py-2 text-lg rounded-3xl text-center w-full' href='https://ufile.io/b50kt2bq'>Resume</Link>
            </div>
          </div>
          <div className='w-screen overflow-x-auto'>
            <div className='justify-start mx-8 h-10 flex gap-10 items-center lg:justify-between'>
              <Link className='hover:text-red-600 hover:underline hover:text-xl transition-all font-bold' href="/">HOME</Link>
              <Link className='hover:text-red-600 hover:underline hover:text-xl transition-all font-bold' href="/videos">VIDEOS</Link>
              <Link className='hover:text-red-600 hover:underline hover:text-xl transition-all font-bold' href="/programming">PROGRAMMING</Link>
              <Link className='hover:text-red-600 hover:underline hover:text-xl transition-all font-bold' href="/skills">SKILLS</Link>
              <Link className='hover:text-red-600 hover:underline hover:text-xl transition-all font-bold' href="/about">ABOUT</Link>
              <Link className='hover:text-red-600 hover:underline pr-8 lg:pr-0 hover:text-xl transition-all font-bold' href="/contact">CONTACT</Link>
            </div>
          </div>
          

        </header>
        <main className="py-20">{children}</main>

        <footer className='text-zinc-400 w-screen'>
          <p className='flex items-center text-xs md:text-sm justify-center'>CopyRight &#169; 2023 Muhammad Mohsin  All Rights Reserved</p>
        </footer>
      </body>
    </html>
  )
}
