import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { FaArrowTurnUp } from "react-icons/fa6";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-6xl mx-auto" >
        <Link href="/" className='flex items-center py-4 justify-center text-2xl font-bold'>ReBlogg</Link>
        <div className='px-10 py-5 mb-10 flex flex-col lg:flex-row lg:space-x-5 justify-between'>
          <div>
            <h1 className='text-5xl mb-4 font-bold'>Lorem's Daily <span className='text-slate-400'>Blogs</span></h1>
            <h2>ReDesigning the <span className='underline decoration-2 decoration-slate-400'>Art of Blogging</span>.</h2>
          </div>
          <p className='max-w-sm text-gray-200 md:mt-2'>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sapiente, quisquam deserunt. Ipsa possimus illo autem.
          </p>
        </div>
        <div className='p-8'>
          {children}
        </div>
        <div className='h-20 w-full flex items-center justify-center'>
          <Link className='flex text-gray-500 items-center justify-center' href="/">
            <p className='px-4'>Back to Home Page</p>
            <FaArrowTurnUp />
          </Link>
        </div>
      </body>
    </html>
  )
}
